### PR TITLE
Get username using gcloud

### PR DESCRIPTION
**Pull request by privacywill**
1. Reserve only one environment variable template: `.env.example`. Developers don't need to determine multiuser or single user any more. 
2. Get username by `gcloud config get-value account` and remove the email suffix. For example, the username `will.privacy@gamil.com`, only `will` is reserved. The username should not contain any special characters such as `.`.

### CODE REVIEW

**Comment by privacywill** [comment]
I modify the command in `.github/workflows/pr.yml` to `run: cp .env.example env.bzl` to pass the pr check. https://github.com/manatee-project/manatee/pull/12/commits/2d5228d38ef3129517930922dfcce032cb0c5527

**Comment by dayeol** [comment]
Actually, can we completely remove the `username` instead, as we discussed before?
Fetching username from gcloud is too implicit.

Here is my suggestion:

The places we use username is (1) k8s namespaces and (2) admin role bindings.
For (1), we basically have a mandatory flag `--namespace` to `deploy.sh` which has no defaults (user MUST provide this value).
For (2), come to think of it, I think admin binding should not be automatically managed by Terraform. It should be manually managed by the owner of the cluster (Otherwise everyone will get cluster admin role, and also this terraform rule requires everyone to have permission to add admin binding).

We initially assumed that everyone will create their own cluster. Instead, we should assume that cluster is ideally created only once, and managed by some project owner.

Ideally, terraform will be ran only once by the project owner or SRE, and it will create all required cloud resources.
After that, the developers should just build and deploy things to the existing cloud resources.

**Comment by jianlinjiang** [comment]
> Actually, can we completely remove the `username` instead, as we discussed before? Fetching username from gcloud is too implicit.
> 
> Here is my suggestion:
> 
> The places we use username is (1) k8s namespaces and (2) admin role bindings. For (1), we basically have a mandatory flag `--namespace` to `deploy.sh` which has no defaults (user MUST provide this value). For (2), come to think of it, I think admin binding should not be automatically managed by Terraform. It should be manually managed by the owner of the cluster (Otherwise everyone will get cluster admin role, and also this terraform rule requires everyone to have permission to add admin binding).
> 
> We initially assumed that everyone will create their own cluster. Instead, we should assume that cluster is ideally created only once, and managed by some project owner. In other words, terraform will be ran only once by the project owner or SRE, and it will create all required cloud resources. After that, the developers should just build and deploy things to the existing cloud resources.

Sure, I think it's also a good idea to remove username entirely. I will create a new PR and close it.
For (2), just remind, If we remove admin binding from Terraform, the project owner should grant the new developer with the permission manually before deploying.

**Comment by privacywill** [comment]
Sure, I think it's ok to remove username entirely. Let me close this and re-open a new PR.
For (2), just remind, the project owner should grant the developer the permission before deploying.

**Pull request closed without merging**
