### PR TITLE
Add GitHub workflow for checking code format

### PR DESCRIPTION
**Pull request by hiunshim**
This PR solves #17 

Add an Action to enforce Go code formatting using `gofmt` and block unformatted code. This PR intentionally excludes lint since it requires external dependencies. It also intentionally doesn't auto-commit formatted code on push, as preferences vary.

#### Changes
- **Workflow**: `lint.yaml` checks formatting using `gofmt`. Named "lint.yaml" instead of "check-format.yaml" because it's meant to be extended in the future.

#### Future Improvements
1. Consider other lint options such as line length, typo, and case-consistency.
2. Consider auto-committing format/lint fixes after making a PR.

#### Usage
- **Locally**:
  - Run `bazelisk run @go_sdk//:bin/gofmt -- -w .`
- **CI/CD**:
  - Runs on `pull_request`.

### CODE REVIEW

**Comment by dayeol** [comment]
Hi @hiunshim!

Thank you for the PR!

We use [Bazel](https://bazel.build/) instead of `Make` for our build system.
In Bazel, we already import `rules_go`, which includes the SDK with `gofmt` binary in it.
Thus, you can run the following command to invoke `gofmt` without installing anything

```
bazelisk run @go_sdk//:bin/gofmt -- -w .
```

Could you please change it to use the bazel command, instead of make?
Also, I think CI/CD needs to fail if gofmt changes any file after running it.

**Comment by hiunshim** [comment]
Hi @dayeol!

Thank you for reviewing the PR and giving me detailed explanation.
I updated it to use Bazel instead of Make as requested.

I considered two options:
1. format _all_ go files
2. format only _staged_ files (through git diff)

I think option 1 is sufficient at the moment so I chose that. I'll include option 2 [code snippet](https://gist.github.com/hiunshim/9df4ab32e597863079cad4fb7b788819) for future reference. Option 2 has been tested separately as well, but the overhead was unclear compared to option 1.

**Tests**
CICD Passing Test: https://github.com/hiunshim/manatee/actions/runs/12444917699
CICD Breaking Test: https://github.com/hiunshim/manatee/actions/runs/12444919510


Screenshot 2024-12-21 at 4 13 19 AM

**Comment by dayeol** [comment]
@hiunshim Thank you! This PR LGTM.

**Review by dayeol — APPROVED** [review]

**Comment by hiunshim** [comment]
@dayeol Awesome! Could you please merge it? It says "Merging is blocked - Merge is not an allowed merge method in this repository. Only those with write access to this repository can merge pull requests."

**Pull request merged**
